apiVersion: v1
name: falco-operator
version: 1.0.0
appVersion: 0.11.1+1
description: (Unofficial) Sysdig Falco Operator
keywords:
  - monitoring
  - security
  - alerting
  - metric
  - troubleshooting
  - run-time
  - operator
home: https://github.com/mumoshu/falco-operator
sources:
  - https://github.com/mumoshu/falco-operator
maintainers:
  - name: mumoshu
    email: ykuoka@gmail.com
